#!/bin/bash
#
# Turn Beaglebone Black GPIO pins on or off. Works with the Beaglebone
# sysfs tree in 4.4 kernels.
#
# Copyright (c)2017 Eric Douglas
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

GPIO_DIR=/sys/class/gpio

function usage () {
  echo "usage: `basename $0` GPIONUM {on|off}"
  exit 1
}

gpio=$1
state=$2

if ! [[ "${gpio}" =~ ^[0-9]+$ ]] ; then
  usage
fi

if ! [[ "${state}" =~ ^(0|1|on|off)$ ]] ; then
  usage
fi

pin_dir="/sys/class/gpio/gpio${gpio}"
direction="${pin_dir}/direction"
value="${pin_dir}/value"

if [ ! -d "$pin_dir" ] ; then
  echo "$gpio" > "${GPIO_DIR}/export"
  sleep 1
fi

echo "out" > "$direction"

case "$state" in
  0|off)
    echo "0" > "$value"
    ;;
  1|on)
    echo "1" > "$value"
esac

exit 0
